# Generated by Django 5.2.7 on 2025-11-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cronjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(editable=False, max_length=100, verbose_name='app')),
                ('job_name', models.CharField(editable=False, max_length=100, verbose_name='job')),
                ('cron_expression', models.CharField(default='* * * * *', help_text="\n            Use expressions in standard CRON format:<br/>\n            <code>minute hour day month day-of-week</code><br/>\n            More details:\n            <a href='https://help.ubuntu.com/community/CronHowto'>CronHowTo</a>\n            ", max_length=100, verbose_name='CRON expression')),
                ('log_duration', models.PositiveIntegerField(default=30, help_text='Number of days that execution logs will be kept in the database. Zero means the log will never be deleted.', verbose_name='days to retain log')),
                ('email_recipient', models.TextField(blank=True, help_text='E-mails to send job execution reports.<br/>Enter one email address per line. Leave empty to not send e-mail reports', verbose_name='email recipient(s)')),
                ('digest_days', models.PositiveIntegerField(default=0, help_text='How many days to wait to make a summary of reports.<br/>zero means the email should be sent immediately after execution.', verbose_name='days to digest')),
                ('error_only', models.BooleanField(default=False, help_text='Send reports by email only when job execution error occurs', verbose_name='report just errors')),
                ('last_digest', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last digest submission')),
            ],
            options={
                'verbose_name': 'Cron job',
                'verbose_name_plural': 'Cron jobs',
                'ordering': ('app_name', 'job_name'),
            },
        ),
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start at')),
                ('started', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('R', 'Running'), ('F', 'Finished')], default='S', max_length=1, verbose_name='status')),
                ('time_spent', models.DurationField(blank=True, editable=False, null=True, verbose_name='time spent on execution')),
                ('result', models.TextField(blank=True, editable=False, verbose_name='execution result')),
                ('has_errors', models.BooleanField(editable=False, null=True, verbose_name='has errors')),
                ('reported', models.BooleanField(default=False, editable=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_controller.cronjob', verbose_name='cron job')),
            ],
            options={
                'verbose_name': 'run schedule',
                'verbose_name_plural': 'run schedules',
                'ordering': ('-start',),
            },
        ),
    ]
