# Generated by Django 6.0.4 on 2026-08-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_controller", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cronjob",
            options={
                "ordering": ("app_name", "job_name"),
                "verbose_name": "Job de cron",
                "verbose_name_plural": "Jobs de cron",
            },
        ),
        migrations.AlterModelOptions(
            name="jobschedule",
            options={
                "ordering": ("-start",),
                "verbose_name": "executar agendamento",
                "verbose_name_plural": "executar agendamentos",
            },
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="app_name",
            field=models.CharField(
                editable=False, max_length=100, verbose_name="aplicativo"
            ),
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="cron_expression",
            field=models.CharField(
                default="* * * * *",
                help_text="\n            Use expressões no formato padrão do CRON:<br/>\n            <code>minuto hora dia mês dia-da-semana</code><br/>\n            Mais detalhes:\n            <a href='https://help.ubuntu.com/community/CronHowto'>CronHowTo</a>\n            ",
                max_length=100,
                verbose_name="expressão CRON",
            ),
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="digest_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Quantos dias esperar para fazer um sumário dos relatórios.<br/>zero significa que o e-mail com relatório deve ser enviado imediatamente após a execução.",
                verbose_name="Dias para digest",
            ),
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="email_recipient",
            field=models.TextField(
                blank=True,
                help_text="E-mails para enviar relatórios de execução do job.<br/>Entre um endereço de e-mail por linha. Deixe vazio para não enviar relatórios por e-mail",
                verbose_name="caixa(s) de e-mail",
            ),
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="error_only",
            field=models.BooleanField(
                default=False,
                help_text="Enviar relatórios por e-mail apenas quando ocorrer erros na execução do job",
                verbose_name="reportar apenas erros",
            ),
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="last_digest",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="último envio do resumo",
            ),
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="log_duration",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Número de dias que os logs de execução serão mantidos no banco de dados. Zero significa que os log nunca devem ser apagados.",
                verbose_name="dias para reter log",
            ),
        ),
        migrations.AlterField(
            model_name="jobschedule",
            name="has_errors",
            field=models.BooleanField(
                editable=False, null=True, verbose_name="possui erros"
            ),
        ),
        migrations.AlterField(
            model_name="jobschedule",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="job_controller.cronjob",
                verbose_name="job de cron",
            ),
        ),
        migrations.AlterField(
            model_name="jobschedule",
            name="result",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="resultado da execução",
            ),
        ),
        migrations.AlterField(
            model_name="jobschedule",
            name="start",
            field=models.DateTimeField(verbose_name="iniciar em"),
        ),
        migrations.AlterField(
            model_name="jobschedule",
            name="started",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="iniciado em"
            ),
        ),
        migrations.AlterField(
            model_name="jobschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("S", "Agendado"),
                    ("R", "Executando"),
                    ("F", "Concluído"),
                ],
                default="S",
                max_length=1,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="jobschedule",
            name="time_spent",
            field=models.DurationField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="tempo gasto na execução",
            ),
        ),
    ]
