# Generated by Django 6.0.4 on 2026-08-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_controller",
            "0002_alter_cronjob_options_alter_jobschedule_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cronjob",
            name="never_execute",
            field=models.BooleanField(
                default=False, verbose_name="Never execute this job"
            ),
        ),
    ]
